spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
     ddl-auto: create
  datasource:
    url:  jdbc:mysql://35.200.178.58:3306/gpstrackerproject
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: arafat_001
server:
  port: 5000