spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
     ddl-auto: create
  datasource:
    url:  jdbc:mysql://35.229.104.163:9003
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: my-secret-pw
server:
  port: 5000
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

bucketName: komenfiles